-- ============================================================
-- Don Ramón Pâtisserie
-- Nuevas tablas para promociones y sus productos/variantes
-- ============================================================

-- Imagen del producto. Mantiene icono si existe, para compatibilidad.
ALTER TABLE productos
ADD COLUMN IF NOT EXISTS imagen_url text;

-- ============================================================
-- PROMOCIONES
-- ============================================================
CREATE TABLE IF NOT EXISTS promociones (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre text NOT NULL,
    descripcion text,
    precio numeric(12,2) NOT NULL CHECK (precio >= 0),
    bcondicion boolean NOT NULL DEFAULT true,
    fecha_desde date,
    fecha_hasta date,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT promociones_fechas_validas
        CHECK (fecha_hasta IS NULL OR fecha_desde IS NULL OR fecha_hasta >= fecha_desde)
);

-- Productos/variantes que componen cada promoción.
-- Se referencia producto_precios para que una promo pueda ser,
-- por ejemplo, "Latte Chico + Cookie" y no cualquier tamaño de Latte.
CREATE TABLE IF NOT EXISTS promocion_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    promocion_id bigint NOT NULL REFERENCES promociones(id) ON DELETE CASCADE,
    producto_precio_id bigint NOT NULL REFERENCES producto_precios(id) ON DELETE RESTRICT,
    cantidad numeric(10,2) NOT NULL DEFAULT 1 CHECK (cantidad > 0),
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT promocion_items_unicos UNIQUE (promocion_id, producto_precio_id)
);

CREATE INDEX IF NOT EXISTS idx_promociones_bcondicion
    ON promociones (bcondicion);

CREATE INDEX IF NOT EXISTS idx_promociones_fechas
    ON promociones (fecha_desde, fecha_hasta);

CREATE INDEX IF NOT EXISTS idx_promocion_items_promocion
    ON promocion_items (promocion_id);

CREATE INDEX IF NOT EXISTS idx_promocion_items_precio
    ON promocion_items (producto_precio_id);

-- ============================================================
-- DATOS DE EJEMPLO
-- No se ejecuta automáticamente. Sirve como referencia.
-- ============================================================
-- INSERT INTO promociones (nombre, descripcion, precio)
-- VALUES ('Café + Cookie', 'Café con una cookie', 5500);
--
-- INSERT INTO promocion_items (promocion_id, producto_precio_id, cantidad)
-- VALUES
--     (1, 10, 1), -- variante de café, por ejemplo Latte Chico
--     (1, 25, 1); -- variante de Cookie

-- ============================================================
-- NOTA SOBRE RLS
-- ============================================================
-- Si las tablas actuales tienen RLS habilitado, deben agregarse
-- políticas equivalentes a las que ya utiliza tu proyecto.
-- No se agregan aquí políticas genéricas para no abrir permisos
-- que actualmente puedan estar restringidos.